import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        {/* ヘッダー */}
        <div className="navbar bg-base-100">
          <a className="btn btn-ghost normal-case text-xl">daisyUI</a>
        </div>
        <div className='grid grid-cols-3 gap-2'>
          <div className="content bg-green-300 col-span-2">
            <p>コンテンツ</p>
          </div>
          <div className="Navigation bg-green-300">
            <p>ナビゲーション</p>
          </div>
        </div>
      </main>
    </>
  )
}
